import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar.js'
import Heading from '../components/heading'
import Projects from '../components/projects'
import Contact from '../components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='text-white w-screen min-h-screen bg-gradient-to-r from-gray-800 to-gray-900'>
      <Head>
        <title>portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=''>
        {/* navbar */}
        <Navbar/>
        {/* heading */}
        <Heading/>
        {/* projects */}
        <Projects/>
        {/* contact */}
        <Contact />
        {/* footer */}
      </div>
    </div>
  )
}
